from alpha_cc.agents.value_assignment.default_assignment_strategy import DefaultAssignmentStrategy
from alpha_cc.agents.value_assignment.value_assignment_strategy import NoOpAssignmentStrategy, ValueAssignmentStrategy
