FROM node:lts-slim AS builder
ENV WORKDIR=/code
RUN mkdir -p ${WORKDIR}
WORKDIR ${WORKDIR}
COPY webapp $WORKDIR
RUN npm install -g @angular/cli && \
    npm install                 && \
    npm run build


FROM nginx AS webapp
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /code/dist/webapp/browser /usr/share/nginx/html
