services:
  trainer:
    image: alpha-cc/training
    build:
      dockerfile: Dockerfile
      target: training
    depends_on:
      - redis
    volumes:
      - local:/mnt:rw
    env_file:
      - .env.docker
    command: [
      "alpha-cc-trainer",
      "--run-id=dbg-101-size-7-01",
      "--size=7",
      "--n-train-samples=10000",
      "--replay-buffer-size=50000",
      "--epochs-per-update=10",
      "--policy-weight=1.0",
      "--value-weight=1.0",
      "--batch-size=256",
      "--lr=1e-4",
    ]

  worker:
    image: alpha-cc/training
    depends_on:
      - trainer
    env_file:
      - .env.docker
    scale: 6
    restart: always
    command: [
      "alpha-cc-worker",
      "--size=7",
      "--n-rollouts=100",
      "--rollout-depth=100",
      "--max-game-length=100000",
      "--dirichlet-noise-weight=0.25",
      "--argmax-delay=40",
    ]
    
  nn-service:
    image: alpha-cc/training
    depends_on:
      - trainer
    env_file:
      - .env.docker
    command: [
      "alpha-cc-nn-service",
      "--size=7",
    ]

  tensorboard:
    image: tensorflow/tensorflow
    network_mode: host
    depends_on:
      - trainer
    volumes:
      - local:/mnt:ro

  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 15
      start_period: 5s

volumes:
  local:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./data"
