[package]
name = "alpha-cc-engine"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "alpha_cc_engine"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.2", features = ["extension-module"] }
bincode = { version = "2.0.1", features = ["serde"] }
indexmap = "2.2.6"
redis = "0.31.0"
rand_distr = "0.4.3"
rand = "0.8.5"
lru = "0.14.0"
memcache = "0.18.0"
zmq = "0.10.0"
lazy_static = "1.5.0"
